import pytest
from unittest.mock import AsyncMock, MagicMock, patch
from pathlib import Path

from backend.app.services.print_scheduler import PrintScheduler
from backend.app.services.elegoo_client import ElegooCentauriClient, map_bed_type_to_elegoo_platform_type


def test_map_bed_type_to_elegoo_platform_type():
    assert map_bed_type_to_elegoo_platform_type("Textured PEI Plate") == 0
    assert map_bed_type_to_elegoo_platform_type("High Temp Plate") == 1
    assert map_bed_type_to_elegoo_platform_type("Smooth PEI Plate") == 1
    assert map_bed_type_to_elegoo_platform_type("Engineering Plate") == 2
    assert map_bed_type_to_elegoo_platform_type("Cool Plate") == 1
    assert map_bed_type_to_elegoo_platform_type("SuperTack Plate") == 4
    assert map_bed_type_to_elegoo_platform_type("Unknown") == 0
    assert map_bed_type_to_elegoo_platform_type(None) == 0


def test_extract_bed_type_and_metadata_from_gcode():
    from backend.app.utils.threemf_tools import extract_bed_type_from_gcode, extract_gcode_metadata

    sample_gcode = """; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2
; total layer number: 253
; nozzle_diameter = 0.4
; layer_height = 0.12
; curr_bed_type:Cool Plate
M140 S35
; filament_type = PLA
"""
    assert extract_bed_type_from_gcode(sample_gcode) == "Cool Plate"
    meta = extract_gcode_metadata(sample_gcode)
    assert meta["bed_type"] == "Cool Plate"
    assert meta["total_layers"] == 253
    assert meta["nozzle_diameter"] == 0.4
    assert meta["layer_height"] == 0.12
    assert meta["filament_type"] == "PLA"
    assert meta["bed_temperature"] == 35.0


@pytest.mark.asyncio
async def test_elegoo_client_start_print_passes_platform_type():
    client = ElegooCentauriClient(
        ip_address="192.168.1.50",
        serial_number="ELEGOO999",
        access_code="123456",
        model="Centauri Carbon",
    )
    mock_printer = MagicMock()
    mock_printer.start_print = AsyncMock()
    client._printer = mock_printer
    client._loop = MagicMock()

    # Start print with Engineering Plate
    client.start_print("model.gcode", plate_id=1, bed_type="Engineering Plate")

    mock_printer.start_print.assert_called_with(
        "model.gcode",
        storage="local",
        auto_leveling=True,
        timelapse=False,
        platform_type=2,
    )
